name: techtrack
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.15.5
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  flutter:
    sdk: flutter
  logger: ^2.0.2+1
  table_calendar: ^3.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
